{
  try {
    return invocation.proceed();
  }
 catch (  Throwable t) {
    handleInCallerTx(invocation,t,tx);
  }
  throw new RuntimeException("UNREACHABLE");
}
