{
  try {
    this.onBeforeInvocation(wsInvocation);
  }
 catch (  Throwable t) {
    this.log.error("Method invocation failed with exception: " + t.getMessage(),t);
    this.handleInvocationException(t);
  }
 finally {
    this.onAfterInvocation(wsInvocation);
  }
}
