{
  try {
    lookup("java:global/interceptors-exceptions/PitcherBean",PitcherBean.class).fastball();
    fail("Should have thrown a (Runtime)Exception");
  }
 catch (  Exception e) {
    assertTrue("Did not declare exception - " + e,e instanceof RuntimeException);
  }
}
