{
  ParticipantCompletionCoordinatorRules.setParticipantCount(3);
  try {
    uba.begin();
    client1.saveData(DO_COMPLETE);
    client2.saveData(DO_COMPLETE);
    client3.saveData();
    uba.close();
    Assert.fail("Exception should have been thrown by now");
  }
 catch (  TransactionRolledBackException e) {
  }
  assertEventLogClient1(CONFIRM_COMPLETED,COMPENSATE);
  assertEventLogClient2(CONFIRM_COMPLETED,COMPENSATE);
  assertEventLogClient3(CANCEL);
}
