{
  try {
    context.proceed();
  }
 catch (  Exception e) {
    ROOT_LOGGER.asyncInvocationFailed(e);
  }
  return;
}
