{
  for (  final CleanupTask task : tasks) {
    try {
      task.cleanup();
    }
 catch (    Exception e) {
      PatchLogger.ROOT_LOGGER.debugf(e,"exception when trying to cleanup up (%s)",task);
    }
  }
}
