{
  try {
    performCall(reqspec);
    Assert.fail("IOException expected");
  }
 catch (  IOException ex) {
  }
}
