{
  try {
    return invocation.proceed();
  }
 catch (  Throwable t) {
    handleExceptionInNoTx(invocation,t,component);
  }
  throw new RuntimeException("UNREACHABLE");
}
