{
  try {
    bean.throwXmlAppException();
    Assert.fail("should have thrown exception");
  }
 catch (  XmlAppException e) {
  }
}
