{
  try {
    uba.begin();
    client1.saveData();
    client2.saveData(CANNOT_COMPLETE);
    client3.saveData();
    uba.close();
    Assert.fail("Exception should have been thrown by now");
  }
 catch (  javax.xml.ws.soap.SOAPFaultException sfe) {
    uba.cancel();
  }
 finally {
    assertEventLogClient1(CANCEL);
    assertEventLogClient2();
    assertEventLogClient3();
  }
}
