{
  final NamingException exception=new NamingException(message);
  if (cause != null)   exception.initCause(cause);
  return exception;
}
